#!/usr/bin/env bash
# Detect Operating System and Update config.toml
#
# This script automatically detects the current operating system
# and updates config.toml with system information for AI agents.
#
# Usage:
#   ./.scaffolding/scripts/detect-os.sh

set -e

# Get the project root directory (2 levels up from this script)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/config.toml"

# Detect OS
detect_os() {
    local os_type=""
    local os_version=""
    local shell_type="$SHELL"
    
    case "$(uname -s)" in
        Darwin*)
            os_type="macOS"
            os_version=$(sw_vers -productVersion 2>/dev/null || echo "unknown")
            ;;
        Linux*)
            os_type="Linux"
            if [ -f /etc/os-release ]; then
                os_version=$(grep "^PRETTY_NAME" /etc/os-release | cut -d'"' -f2)
            else
                os_version=$(uname -r)
            fi
            ;;
        CYGWIN*|MINGW*|MSYS*)
            os_type="Windows"
            os_version=$(cmd.exe /c ver 2>/dev/null | grep "Version" || echo "unknown")
            ;;
        *)
            os_type="Unknown"
            os_version="unknown"
            ;;
    esac
    
    echo "$os_type|$os_version|$shell_type"
}

# Update or add [system] section in config.toml
update_config() {
    local os_info=$1
    IFS='|' read -r os_type os_version shell_type <<< "$os_info"
    
    # Check if config.toml exists
    if [ ! -f "$CONFIG_FILE" ]; then
        echo "⚠️  Warning: config.toml not found at $CONFIG_FILE"
        echo "   Creating from config.toml.example..."
        if [ -f "$PROJECT_ROOT/config.toml.example" ]; then
            cp "$PROJECT_ROOT/config.toml.example" "$CONFIG_FILE"
        else
            echo "❌ Error: config.toml.example not found"
            exit 1
        fi
    fi
    
    # Remove existing [system] section if exists
    if grep -q "^\[system\]" "$CONFIG_FILE"; then
        # Use different approach for macOS vs Linux sed
        if [[ "$os_type" == "macOS" ]]; then
            sed -i '' '/^\[system\]/,/^$/d' "$CONFIG_FILE"
        else
            sed -i '/^\[system\]/,/^$/d' "$CONFIG_FILE"
        fi
    fi
    
    # Append [system] section at the end
    cat >> "$CONFIG_FILE" <<EOF

# ==============================================================================
# System Information (Auto-detected)
# ==============================================================================
# This section is automatically generated by .scaffolding/scripts/detect-os.sh
# AI agents use this information to select appropriate commands and tools.
#
# Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

[system]
os_type = "$os_type"
os_version = "$os_version"
shell = "$shell_type"

# Command availability hints for AI agents
[system.commands]
# Package managers
has_brew = $(command -v brew &>/dev/null && echo "true" || echo "false")
has_apt = $(command -v apt &>/dev/null && echo "true" || echo "false")
has_yum = $(command -v yum &>/dev/null && echo "true" || echo "false")
has_choco = $(command -v choco &>/dev/null && echo "true" || echo "false")

# Utilities (macOS vs Linux differences)
timeout_command = "$(if command -v gtimeout &>/dev/null; then echo 'gtimeout'; elif command -v timeout &>/dev/null; then echo 'timeout'; else echo 'none'; fi)"
sed_inplace = "$(if [[ "$os_type" == "macOS" ]]; then echo "sed -i ''"; else echo "sed -i"; fi)"
readlink_canonical = "$(if [[ "$os_type" == "macOS" ]]; then echo "greadlink -f"; else echo "readlink -f"; fi)"

# Development tools
has_docker = $(command -v docker &>/dev/null && echo "true" || echo "false")
has_git = $(command -v git &>/dev/null && echo "true" || echo "false")
has_node = $(command -v node &>/dev/null && echo "true" || echo "false")
has_python = $(command -v python3 &>/dev/null && echo "true" || echo "false")
has_bun = $(command -v bun &>/dev/null && echo "true" || echo "false")
has_uv = $(command -v uv &>/dev/null && echo "true" || echo "false")
EOF
    
    echo "✓ System information updated in config.toml"
    echo ""
    echo "Detected:"
    echo "  OS: $os_type $os_version"
    echo "  Shell: $shell_type"
}

# Main
main() {
    echo "🔍 Detecting operating system..."
    echo ""
    
    os_info=$(detect_os)
    update_config "$os_info"
    
    echo ""
    echo "AI agents can now use this information from config.toml:"
    echo "  - Select correct commands (timeout vs gtimeout)"
    echo "  - Choose appropriate package managers"
    echo "  - Use correct sed syntax (macOS vs Linux)"
    echo ""
    echo "To update system info, run this script again:"
    echo "  ./.scaffolding/scripts/detect-os.sh"
}

main "$@"
